server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api/swagger-ui

spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  password: rootroot
  url: jdbc:mysql://localhost:3306/BookShop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  username: root

  data:
    cassandra:
      schema-action: create_if_not_exists
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true


  servlet:
    multipart:
      max-file-size: 10MB
  main:
    allow-circular-references: true

# Show Hibernate SQL query
logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret_key: ${JWT_SECRET}
  time_expiration: 86400000

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

cloudinary:
  url: ${CLOUDINARY_URL}

storage:
  location: upload-dir

user:
  firstName: ${USER_FIRST_NAME}
  lastName: ${USER_LAST_NAME}
  username: ${USER_USERNAME}
  password: ${USER_PASSWORD}
  address: ${USER_ADDRESS}
  amount: ${USER_AMOUNT}
  role: ${USER_ROLE}
  email: ${USER_EMAIL}
  phone: ${USER_PHONE}
